sonar.projectKey=MapaReactNativeExpo
sonar.projectName=MapaReactNativeExpo

sonar.sources=.
sonar.exclusions=node_modules/**,android/**,ios/**,.expo/**

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

$